"use client";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";

import { useState, useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";
import SplashScreen from "./components/Splashscreen";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState<boolean>(false);
  const [targetPage, setTargetPage] = useState<string>(""); // Store the next route here
  const pathname = usePathname(); // Get current pathname

  useEffect(() => {
    // Whenever the pathname changes, set the loading state and targetPage
    setTargetPage(pathname); // Set the current route as the target page
    setLoading(true);

    // You can simulate a delay for the splash screen (optional)
    const timeout = setTimeout(() => {
      setLoading(false);
    }, 1000); // This controls how long the splash screen stays visible (1 second)

    // Cleanup the timeout on unmount or on route change
    return () => clearTimeout(timeout);
  }, [pathname]); // Runs every time the pathname changes

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-[#0e090d]`}
      >
        <SplashScreen loading={loading} targetPage={targetPage} />
        <Sidebar />
        <main> {children}</main>
      </body>
    </html>
  );
}
