"use client";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Head from 'next/head';
import { useState, useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";
import SplashScreen from "./components/Splashscreen";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState<boolean>(false);
  const [targetPage, setTargetPage] = useState<string>(""); // Store the next route here
  const pathname = usePathname(); // Get current pathname

  useEffect(() => {
    // Whenever the pathname changes, set the loading state and targetPage
    setTargetPage(pathname); // Set the current route as the target page
    setLoading(true);

    // You can simulate a delay for the splash screen (optional)
    const timeout = setTimeout(() => {
      setLoading(false);
    }, 1000); // This controls how long the splash screen stays visible (1 second)

    // Cleanup the timeout on unmount or on route change
    return () => clearTimeout(timeout);
  }, [pathname]); // Runs every time the pathname changes

  return (
    <html lang="en">
      <Head>
        {/* Default SEO Settings */}
        <title>Oluwatimilehin Rotimi</title>
        <meta name="description" content="Oluwatimilehin Rotimi ePortfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        {/* Open Graph Meta Tags */}
        <meta property="og:title" content="Oluwatimilehin Rotimi" />
        <meta property="og:description" content="Oluwatimilehin Rotimi ePortfolio" />
        {/* <meta property="og:image" content="/" />
        <meta property="og:url" content="https://example.com" />
        <meta property="og:type" content="website" /> */}

        {/* Twitter Card Meta Tags */}
        {/* <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@username" />
        <meta name="twitter:title" content="My Next.js App" />
        <meta name="twitter:description" content="This is a sample Next.js app with SEO best practices." />
        <meta name="twitter:image" content="https://example.com/default-image.jpg" /> */}

        {/* Favicon */}
        {/* <link rel="icon" href="/favicon.ico" /> */}

        {/* Canonical URL */}
        {/* <link rel="canonical" href="https://example.com" /> */}
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-[#0e090d]`}
      >
        <SplashScreen loading={loading} targetPage={targetPage} />
        <Sidebar />
        <main> {children}</main>
      </body>
    </html>
  );
}
