"use client";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Head from 'next/head';
import { useState, useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";
import SplashScreen from "./components/Splashscreen";
import timi from './assets/oluwatimilehin.jpg'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState<boolean>(false);
  const [targetPage, setTargetPage] = useState<string>(""); // Store the next route here
  const pathname = usePathname(); // Get current pathname

  useEffect(() => {
    // Whenever the pathname changes, set the loading state and targetPage
    setTargetPage(pathname); // Set the current route as the target page
    setLoading(true);

    // You can simulate a delay for the splash screen (optional)
    const timeout = setTimeout(() => {
      setLoading(false);
    }, 1000); // This controls how long the splash screen stays visible (1 second)

    // Cleanup the timeout on unmount or on route change
    return () => clearTimeout(timeout);
  }, [pathname]); // Runs every time the pathname changes

  return (
    <html lang="en">
      <Head>
        {/* <!-- Title --> */}
        <title>Oluwatimilehin Rotimi | Frontend Developer</title>

        {/* <!-- Meta Tags for SEO --> */}
        <meta name="description" content="Oluwatimilehin Rotimi is a frontend developer with a unique talent of creating innovative, aesthetic solutions in a short amount of time." />
        <meta property="og:title" content="Oluwatimilehin Rotimi | Frontend Developer" />
        <meta property="og:description" content="Work with Oluwatimilehin Rotimi, a trusted frontend developer with an obsession with perfection and functionality." />
        <meta property="og:image" content="./assets/oluwatimilehin.jpg" />
        <meta property="og:url" content="https://oluwatimilehin-eportfolio.vercel.app" />

        {/* <!-- Favicon --> */}
        <link rel="icon" type="image/svg+xml" href="./assets/oluwatimilehin.jpg" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth bg-[#0e090d]`}
      >
        <SplashScreen loading={loading} targetPage={targetPage} />
        <Sidebar />
        <main> {children}</main>
      </body>
    </html>
  );
}
